### ISSUE TITLE
Internet suggestion to doctor Nilesh Mali: Research and give him suggestion for internet connection

### ISSUE THREAD

**Issue by shilpikhemka11** [shilpikhemka11/MedDNA-Marketing#10]

**Comment by wrushin** [comment]
VOVINET broadband with 10MBps truly unlimited for a whole month10 Mbps  999 http://vovinet.in/broadband.html#smartpacks

**Comment by wrushin** [comment]
Vodafone
Name                           Base Price       Validity  
3G Data Plan 100b   ₹ 100.0   1 Month
3G Data Plan 250b   ₹ 250.0   1 Month
3G Data Plan 450              ₹ 450.0 1 Month
3G Unlimited Data Plan 650      ₹ 650.0   1 Month
3G Unlimited Data Plan 750   b  ₹ 750.0   1 Month
3G Unlimited Data Plan 850        ₹ 850.0 1 Month

**Comment by shilpikhemka11** [comment]
Call him on Monday , he will come back to Pune. Prescription pad is ready.
