### ISSUE TITLE
Gudi Padwa message for doctors

### ISSUE THREAD

**Issue by shilpikhemka11** [shilpikhemka11/MedDNA-Marketing#7]
Forward message to Shilpi, she will send it to doctors.

**Comment by wrushin** [comment]
1-  May This Gudi Padwa Bring Joy Health & Wealth To U. May The Light That We Celebrate At Gudi Padwa Show Us The Way & Lead Us Together On The Path Of Peace & Social Harmony.

2- Celebrate the auspicious occasion of Gudi Padwa amidst fanfare and religious favor.May the day bestow on you and your family members.My best wishes with you.

**Comment by wrushin** [comment]
Swagat nav varshache.
Asha aakankshache.
Sukh samruddhiche, padata dwari paaul Gudhiche....
